# Generated by Django 2.2.11 on 2020-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm_approach',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm_execution',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_optional', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm_parameter',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm_parameter_value',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithm_type',
            },
        ),
        migrations.CreateModel(
            name='AthleteClustering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'athlete_clustering',
            },
        ),
        migrations.CreateModel(
            name='AthleteClusteringAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('membership', models.DecimalField(decimal_places=3, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'athlete_clustering_assignment',
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('major_version', models.PositiveIntegerField()),
                ('minor_version', models.PositiveIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_browser',
            },
        ),
        migrations.CreateModel(
            name='BrowserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_browser_feature',
            },
        ),
        migrations.CreateModel(
            name='BrowserFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_browser_features',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_device_type',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_ip_address',
            },
        ),
        migrations.CreateModel(
            name='IpAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_ip_address_type',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('major_version', models.PositiveIntegerField(blank=True, null=True)),
                ('minor_version', models.PositiveIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_operating_system',
            },
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_referrer',
            },
        ),
        migrations.CreateModel(
            name='ReferrerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_referrer_type',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type_id', models.PositiveIntegerField()),
                ('identity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer_id', models.BigIntegerField(blank=True, null=True)),
                ('method_id', models.PositiveIntegerField()),
                ('ip_address_id', models.BigIntegerField()),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('browser_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url_id', models.BigIntegerField()),
                ('user_agent_id', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'analytics_request',
            },
        ),
        migrations.CreateModel(
            name='RequestFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_feature',
            },
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_header',
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_header_type',
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_header_value',
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.BigIntegerField()),
                ('header_value_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'analytics_request_header_values',
            },
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_method',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_request_type',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_url',
            },
        ),
        migrations.CreateModel(
            name='UrlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_url_parameter',
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_url_parameter_value',
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValues',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.BigIntegerField()),
                ('parameter_value_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'analytics_url_parameter_values',
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'analytics_user_agent',
            },
        ),
    ]
