# Generated by Django 2.2.11 on 2020-07-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('athletics', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparametervalue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_url_parameter_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='urlparametervalue',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_url_parameter_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='urlparametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.UrlParameter'),
        ),
        migrations.AddField(
            model_name='urlparameter',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_url_parameters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='urlparameter',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_url_parameters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='url',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_urls', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='url',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_urls', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestmethod',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_methods', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestmethod',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_methods', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheadervalue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_header_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheadervalue',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.RequestHeader'),
        ),
        migrations.AddField(
            model_name='requestheadervalue',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_header_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheadertype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_header_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheadertype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_header_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheader',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_headers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheader',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_headers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestheader',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.RequestHeaderType'),
        ),
        migrations.AddField(
            model_name='requestfeature',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_request_features', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.BrowserFeature'),
        ),
        migrations.AddField(
            model_name='requestfeature',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_request_features', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='requestfeature',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.Request'),
        ),
        migrations.AddField(
            model_name='referrertype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_referrer_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='referrertype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_referrer_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='referrer',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_referrers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='referrer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_referrers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='referrer',
            name='referrer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.ReferrerType'),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_operating_systems', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_operating_systems', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ipaddresstype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ip_address_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ipaddresstype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_ip_address_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ip_addresses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ip_address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.IpAddressType'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_ip_addresses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_device_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_device_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_devices', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_devices', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browserfeatures',
            name='analytics_browser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.Browser'),
        ),
        migrations.AddField(
            model_name='browserfeatures',
            name='analytics_browser_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.BrowserFeature'),
        ),
        migrations.AddField(
            model_name='browserfeatures',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_browser_feature_relationships', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browserfeatures',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_browser_feature_relationships', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browserfeature',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_browser_features', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browserfeature',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_browser_features', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browser',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_browsers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='browser',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_browsers', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclusteringassignment',
            name='clustering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.AthleteClustering'),
        ),
        migrations.AddField(
            model_name='athleteclusteringassignment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recent_athlete_clusters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclusteringassignment',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clusters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclusteringassignment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recently_modified_athlete_clusters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='athlete_clustering_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Discipline'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Division'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atlete_clustering_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmtype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithm_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmtype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_algorithm_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithm_parameter_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.AlgorithmExecution'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_algorithm_parameter_values', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.AlgorithmParameter'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.Algorithm'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithm_parameters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_algorithm_parameters', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.Algorithm'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithm_executions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_algorithm_parameter_executions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmapproach',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithm_approaches', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithmapproach',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lasT_modified_algorithm_approaches', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.AlgorithmApproach'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_algorithms', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_algorithms', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.AlgorithmType'),
        ),
        migrations.AlterUniqueTogether(
            name='urlparametervalue',
            unique_together={('parameter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='requestheadervalue',
            unique_together={('header', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='requestfeature',
            unique_together={('request', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='operatingsystem',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('ip_address_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_type', 'manufacturer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='browserfeatures',
            unique_together={('analytics_browser', 'analytics_browser_feature')},
        ),
        migrations.AlterUniqueTogether(
            name='athleteclusteringassignment',
            unique_together={('clustering', 'identity', 'cluster')},
        ),
        migrations.AlterUniqueTogether(
            name='algorithmparametervalue',
            unique_together={('execution', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='algorithmparameter',
            unique_together={('algorithm', 'name')},
        ),
    ]
