# Generated by Django 3.1.4 on 2021-01-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('analytics', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteclusteringassignment',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clusters', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.activity'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.division'),
        ),
        migrations.AddField(
            model_name='athleteclustering',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithmexecution'),
        ),
        migrations.AddField(
            model_name='algorithmparametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithmparameter'),
        ),
        migrations.AddField(
            model_name='algorithmparameter',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithm'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithm'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithmapproach'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.algorithmtype'),
        ),
        migrations.AlterUniqueTogether(
            name='athleteclusteringassignment',
            unique_together={('clustering', 'identity', 'cluster')},
        ),
        migrations.AlterUniqueTogether(
            name='algorithmparametervalue',
            unique_together={('execution', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='algorithmparameter',
            unique_together={('algorithm', 'name')},
        ),
    ]
