# Generated by Django 2.2.14 on 2020-08-02 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ethnicity',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identities', to='identity.Identity')),
            ],
            options={
                'db_table': 'identity',
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identity_types', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identity_types', to='identity.Identity')),
            ],
            options={
                'db_table': 'identity_type',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_type_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_type_last_modified_by', to='identity.Identity')),
            ],
            options={
                'db_table': 'organization_type',
            },
        ),
        migrations.CreateModel(
            name='StagingIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('is_private', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentity_created_by', to='identity.Identity')),
                ('identity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.IdentityType')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentity_last_modified_by', to='identity.Identity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity')),
            ],
            options={
                'db_table': 'staging_identity',
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='trait_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trait_last_modified_by', to='identity.Identity')),
            ],
            options={
                'db_table': 'trait',
            },
        ),
        migrations.CreateModel(
            name='StagingIdentityPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentityperson_created_by', to='identity.Identity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Gender')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentityperson_last_modified_by', to='identity.Identity')),
                ('staging_identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity')),
            ],
            options={
                'db_table': 'staging_identity_person',
            },
        ),
        migrations.CreateModel(
            name='StagingIdentityOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=25)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentityorganization_created_by', to='identity.Identity')),
                ('headquarters_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Location')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingidentityorganization_last_modified_by', to='identity.Identity')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.OrganizationType')),
                ('staging_identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity')),
            ],
            options={
                'db_table': 'staging_identity_organization',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_races', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_races', to='identity.Identity')),
            ],
            options={
                'db_table': 'race',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationmembership_created_by', to='identity.Identity')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='athletics.Division')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationmembership_last_modified_by', to='identity.Identity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationmembership', to='identity.Identity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='identity.Identity')),
            ],
            options={
                'db_table': 'organization_membership',
            },
        ),
        migrations.CreateModel(
            name='IdentityTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=13)),
                ('is_primary', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identity_traits', to='identity.Identity')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identity_traits', to='identity.Identity')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Trait')),
            ],
            options={
                'db_table': 'identity_trait',
            },
        ),
        migrations.CreateModel(
            name='IdentityPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identity_person', to='identity.Identity')),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Ethnicity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Gender')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identity_person', to='identity.Identity')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_persons', to='identity.Race')),
            ],
            options={
                'db_table': 'identity_person',
            },
        ),
        migrations.CreateModel(
            name='IdentityOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identity_organization', to='identity.Identity')),
                ('headquarters_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='headquarted_identity_organizations', to='geography.Location')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identity_organization', to='identity.Identity')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.OrganizationType')),
            ],
            options={
                'db_table': 'identity_organization',
            },
        ),
        migrations.CreateModel(
            name='IdentityCitizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Country')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
            ],
            options={
                'db_table': 'identity_citizenship',
            },
        ),
        migrations.CreateModel(
            name='IdentityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=13)),
                ('is_primary', models.PositiveIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Attribute')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_identity_attribute', to='identity.Identity')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identity_attribute', to='identity.Identity')),
            ],
            options={
                'db_table': 'identity_attribute',
            },
        ),
        migrations.AddField(
            model_name='identity',
            name='identity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.IdentityType'),
        ),
        migrations.AddField(
            model_name='identity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_identities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GoogleLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('azp', models.CharField(max_length=75)),
                ('aud', models.CharField(max_length=75)),
                ('iat', models.PositiveIntegerField()),
                ('exp', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_google_logins', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_google_logins', to='identity.Identity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_login',
            },
        ),
        migrations.AddField(
            model_name='gender',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_genders', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='gender',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_genders', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ethnicity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ethnicities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='ethnicity',
            name='last_modified_by',
            field=models.ForeignKey(db_column='last_modified_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_ethncities', to='identity.Identity'),
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entity_types', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_entity_types', to='identity.Identity')),
            ],
            options={
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='EntityTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=13)),
                ('is_primary', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entity_traits', to='identity.Identity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Entity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_entity_traits', to='identity.Identity')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Trait')),
            ],
            options={
                'db_table': 'entity_trait',
            },
        ),
        migrations.CreateModel(
            name='EntityIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entity_identities', to='identity.Identity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Entity')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_entity_identities', to='identity.Identity')),
            ],
            options={
                'db_table': 'entity_identity',
            },
        ),
        migrations.CreateModel(
            name='EntityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=13)),
                ('is_primary', models.PositiveIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Attribute')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entity_attributes', to='identity.Identity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Entity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_entity_attributes', to='identity.Identity')),
            ],
            options={
                'db_table': 'entity_attribute',
            },
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preferred_indicator', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entity_aliases', to='identity.Identity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Entity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_entity_aliases', to='identity.Identity')),
            ],
            options={
                'db_table': 'entity_alias',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_entities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.EntityType'),
        ),
    ]
