# Generated by Django 3.1.4 on 2021-01-04 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
        ('identity', '0001_initial'),
        ('sport', '0001_initial'),
        ('geography', '0002_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='sport.division'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationmembership_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationmembership', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identitytrait',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identitytrait_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identitytrait',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identitytrait_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identitytrait',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identitytrait',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identitytrait_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identitytrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.trait'),
        ),
        migrations.AddField(
            model_name='identityteam',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityteam_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityteam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityteam_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityteam',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_teams', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityteam',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityteam_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityteam',
            name='team_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.teamtype'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityperson_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityperson_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.ethnicity'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.gender'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityperson_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityperson',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_persons', to='identity.race'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityorganization_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityorganization_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='headquarters_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='headquarted_identity_organizations', to='geography.location'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityorganization_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityorganization',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.organizationtype'),
        ),
        migrations.AddField(
            model_name='identitycitizenship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country'),
        ),
        migrations.AddField(
            model_name='identitycitizenship',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.attribute'),
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityattribute_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityattribute_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identityattribute_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='identity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identitytype'),
        ),
        migrations.AddField(
            model_name='identity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identity_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googlelogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitytrait',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entitytrait_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entitytrait',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entitytrait_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entitytrait',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.entity'),
        ),
        migrations.AddField(
            model_name='entitytrait',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entitytrait_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entitytrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.trait'),
        ),
        migrations.AddField(
            model_name='entityidentity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityidentity_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityidentity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityidentity_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityidentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.entity'),
        ),
        migrations.AddField(
            model_name='entityidentity',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityidentity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityidentity_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.attribute'),
        ),
        migrations.AddField(
            model_name='entityattribute',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityattribute_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityattribute',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityattribute_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityattribute',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.entity'),
        ),
        migrations.AddField(
            model_name='entityattribute',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityattribute_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityalias',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityalias_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityalias',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityalias_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entityalias',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.entity'),
        ),
        migrations.AddField(
            model_name='entityalias',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entityalias_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.entitytype'),
        ),
        migrations.AddField(
            model_name='entity',
            name='knowledge_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utility.knowledgegraph'),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_last_modified', to='identity.identity'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('organization', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='identitytrait',
            unique_together={('identity', 'trait')},
        ),
        migrations.AlterUniqueTogether(
            name='identityorganization',
            unique_together={('identity', 'organization_type', 'headquarters_location')},
        ),
        migrations.AlterUniqueTogether(
            name='identitycitizenship',
            unique_together={('identity', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='identityattribute',
            unique_together={('identity', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('organization', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='entitytrait',
            unique_together={('entity', 'trait')},
        ),
        migrations.AlterUniqueTogether(
            name='entityidentity',
            unique_together={('entity', 'identity')},
        ),
        migrations.AlterUniqueTogether(
            name='entityattribute',
            unique_together={('entity', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('entity_type', 'slug')},
        ),
    ]
