# Generated by Django 3.1.4 on 2021-01-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('major_version', models.PositiveSmallIntegerField()),
                ('minor_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'analytics_browser',
            },
        ),
        migrations.CreateModel(
            name='BrowserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_browser_feature',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_device_type',
            },
        ),
        migrations.CreateModel(
            name='IpAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_ip_address_type',
            },
        ),
        migrations.CreateModel(
            name='ReferrerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_referrer_type',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type_id', models.PositiveSmallIntegerField()),
                ('identity_id', models.BigIntegerField(blank=True, null=True)),
                ('referrer_id', models.BigIntegerField(blank=True, null=True)),
                ('method_id', models.PositiveSmallIntegerField()),
                ('ip_address_id', models.BigIntegerField()),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('browser_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url_id', models.BigIntegerField()),
                ('user_agent_id', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'analytics_request',
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'analytics_request_header_type',
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.BigIntegerField()),
                ('header_value_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'analytics_request_header_values',
            },
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_request_method',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'analytics_request_type',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'analytics_url',
            },
        ),
        migrations.CreateModel(
            name='UrlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'analytics_url_parameter',
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValues',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.BigIntegerField()),
                ('parameter_value_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'analytics_url_parameter_values',
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'analytics_user_agent',
            },
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.requestheadertype')),
            ],
            options={
                'db_table': 'analytics_request_header',
            },
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250)),
                ('referrer_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.referrertype')),
            ],
            options={
                'db_table': 'analytics_referrer',
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.urlparameter')),
            ],
            options={
                'db_table': 'analytics_url_parameter_value',
                'unique_together': {('parameter', 'value')},
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=250)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.requestheader')),
            ],
            options={
                'db_table': 'analytics_request_header_value',
                'unique_together': {('header', 'value')},
            },
        ),
        migrations.CreateModel(
            name='RequestFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supported', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.browserfeature')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.request')),
            ],
            options={
                'db_table': 'analytics_request_feature',
                'unique_together': {('request', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=25)),
                ('major_version', models.PositiveIntegerField(blank=True, null=True)),
                ('minor_version', models.PositiveIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity')),
            ],
            options={
                'db_table': 'analytics_operating_system',
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
                ('ip_address_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.ipaddresstype')),
            ],
            options={
                'db_table': 'analytics_ip_address',
                'unique_together': {('ip_address_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.devicetype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.identity')),
            ],
            options={
                'db_table': 'analytics_device',
                'unique_together': {('device_type', 'manufacturer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BrowserFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supported', models.BooleanField()),
                ('analytics_browser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.browser')),
                ('analytics_browser_feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webanalytics.browserfeature')),
            ],
            options={
                'db_table': 'analytics_browser_features',
                'unique_together': {('analytics_browser', 'analytics_browser_feature')},
            },
        ),
    ]
