# Generated by Django 2.2.9 on 2020-01-12 18:53

from django.db import migrations
import identity
import athletics
import utility
from django.contrib.auth.models import User
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    def add_sport_types(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        sport_types = ['Cardiovascular', 'Strength']

        for name in sport_types:
            try:
                instance = athletics.models.SportType.objects.get(name=name)
            except Exception:
                instance = athletics.models.SportType(name=name, description='', created_by=superuser_identity)
                instance.save()

    def competition_type(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        types = ['Race', 'Trial']

        for name in types:
            try:
                competition_type = athletics.models.CompetitionType.objects.get(name=name)
            except Exception:
                competition_type = athletics.models.Competition(name=name, description='', created_by=superuser_identity)
                competition_type.save()


    def add_sports(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        data = [
            {"sport_type":"Cardiovascular", "name":"Triathlon", "scoring_units":"Second", "knowledge_graph_id":None},
            {"sport_type":"Cardiovascular", "name":"Swimming (sport)", "scoring_units":"Second", "knowledge_graph_id":None},
            {"sport_type":"Cardiovascular", "name":"Wheelchair racing", "scoring_units":"Second", "knowledge_graph_id":None},
            {"sport_type":"Strength", "name":"Olympic weightlifting", "scoring_units":"Kilogram", "knowledge_graph_id":None},
            {"sport_type":"Strength", "name":"Powerlifting", "scoring_units":"Kilogram", "knowledge_graph_id":None},
            {"sport_type":"Strength", "name":"Jumps", "scoring_units":"Meter", "knowledge_graph_id":None},
            {"sport_type":"Strength", "name":"Throws", "scoring_units":"Meter", "knowledge_graph_id":None},
            {"sport_type":"Cardiovascular", "name":"Running", "scoring_units":"Meter", "knowledge_graph_id":None}
        ]

        for item in data:
            sport_name = item['name']
            try:
                instance = athletics.models.Sport.objects.get(name=sport_name)
            except Exception:
                sport_type_name = item['sport_type']
                sport_type = athletics.models.SportType.objects.get(name=sport_type_name)
                units = item['scoring_units']
                unit = utility.models.Unit.objects.get(name=units)
                instance = athletics.models.Sport(sport_type=sport_type, name=sport_name, description='', scoring_units=unit, knowledge_graph_id=None, created_by=superuser_identity)
                instance.save()


    def add_disciplines(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        names = ['Sprints', 'Middle/Long', 'Hurdles', 'Road Running', 'Jumps', 'Throws', 'Combined', 'Relay', 'Cross Country', 'Mountain Running', 'Ultra Running']
        sports = ['Running', 'Running', 'Running', 'Running', 'Jumps', 'Throws', 'Running', 'Running', 'Running', 'Running', 'Running']

        for sport, name in zip(sports, names):
            try:
                instance = athletics.models.Discipline.objects.get(name=name)
            except Exception:
                sport = athletics.models.Sport.objects.get(name=sport)
                instance = athletics.models.Discipline(sport=sport, name=name, description='', created_by=superuser_identity)
                instance.save()

    def add_events(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        events = [{"discipline_id":"1", "name":"High Jump"},
        {"discipline_id":"1", "name":"Pole Vault"},
        {"discipline_id":"1", "name":"Long Jump"},
        {"discipline_id":"1", "name":"Triple Jump"},
        {"discipline_id":"2", "name":"Shot Put"},
        {"discipline_id":"2", "name":"Discus Throw"},
        {"discipline_id":"2", "name":"Hammer Throw"},
        {"discipline_id":"2", "name":"Javelin Throw"},
        {"discipline_id":"6", "name":"Heptathlon"},
        {"discipline_id":"6", "name":"Decathlon"},
        {"discipline_id":"3", "name":"100m", "distance":"100.00"},
        {"discipline_id":"3", "name":"200m", "distance":"200.00"},
        {"discipline_id":"3", "name":"400m", "distance":"400.00"},
        {"discipline_id":"4", "name":"800m", "distance":"800.00"},
        {"discipline_id":"4", "name":"1500m", "distance":"1500.00"},
        {"discipline_id":"5", "name":"5000m", "distance":"5000.00"},
        {"discipline_id":"5", "name":"10000m", "distance":"10000.00"},
        {"discipline_id":"10", "name":"100m Hurdles", "distance":"100.00"},
        {"discipline_id":"10", "name":"400m Hurdles", "distance":"400.00"},
        {"discipline_id":"5", "name":"3000m Steeplechase", "distance":"3000.00"},
        {"discipline_id":"10", "name":"110m Hurdles", "distance":"110.00"},
        {"discipline_id":"5", "name":"Marathon", "distance":"42195.00"},
        {"discipline_id":"5", "name":"3000m", "distance":"3000.00"},
        {"discipline_id":"6", "name":"Pentathlon"},
        {"discipline_id":"3", "name":"100 yards", "distance":"91.44"},
        {"discipline_id":"3", "name":"220 yards", "distance":"201.17"},
        {"discipline_id":"3", "name":"440 yards", "distance":"402.34"},
        {"discipline_id":"4", "name":"880 yards", "distance":"804.67"},
        {"discipline_id":"4", "name":"1 Mile", "distance":"1609.34"},
        {"discipline_id":"5", "name":"2 Miles", "distance":"3218.69"},
        {"discipline_id":"5", "name":"3 Miles", "distance":"4828.03"},
        {"discipline_id":"5", "name":"6 Miles", "distance":"9656.06"},
        {"discipline_id":"10", "name":"440 yards Hurdles", "distance":"402.34"},
        {"discipline_id":"10", "name":"120 YARD HURDLES", "distance":"109.73"},
        {"discipline_id":"10", "name":"80m Hurdles", "distance":"80.00"},
        {"discipline_id":"3", "name":"60m", "distance":"60.00"},
        {"discipline_id":"3", "name":"50 yards", "distance":"45.72"},
        {"discipline_id":"5", "name":"2 Miles Steeple Chase", "distance":"3218.69"},
        {"discipline_id":"3", "name":"50m", "distance":"50.00"},
        {"discipline_id":"2", "name":"8lb Shot put", "weight":"3628.74"},
        {"discipline_id":"3", "name":"200m Straight Track", "distance":"200000.00"},
        {"discipline_id":"3", "name":"200m Slight Turn", "distance":"200.00"},
        {"discipline_id":"3", "name":"220 yards Slight Turn", "distance":"201.17"},
        {"discipline_id":"3", "name":"80y h\/r", "distance":"73.15"},
        {"discipline_id":"3", "name":"220 yards Straight Track", "distance":"201.17"},
        {"discipline_id":"5", "name":"5 Miles", "distance":"8046.72"},
        {"discipline_id":"3", "name":"440 yards Straight Track", "distance":"402.34"},
        {"discipline_id":"5", "name":"20km road", "distance":"20000.00"},
        {"discipline_id":"5", "name":"50km road", "distance":"50000.00"},
        {"discipline_id":"7", "name":"4 x 100m Relay", "distance":"400.00"},
        {"discipline_id":"7", "name":"4 x 400m Relay", "distance":"1600.00"},
        {"discipline_id":"5", "name":"10km road", "distance":"10000.00"},
        {"discipline_id":"5", "name":"10km track", "distance":"10000.00"},
        {"discipline_id":"10", "name":"60m Hurdles", "distance":"60.00"},
        {"discipline_id":"10", "name":"50m Hurdles", "distance":"50.00"},
        {"discipline_id":"5", "name":"30km road", "distance":"30000.00"},
        {"discipline_id":"5", "name":"20 miles road", "distance":"32186.90"},
        {"discipline_id":"7", "name":"4 x 110 yards", "distance":"402.34"},
        {"discipline_id":"7", "name":"4 x 440 yards Relay", "distance":"1609.34"},
        {"discipline_id":"4", "name":"660 yards", "distance":"603.50"},
        {"discipline_id":"5", "name":"4 Miles", "distance":"6437.38"},
        {"discipline_id":"8", "name":"6000m", "distance":"6000.00"},
        {"discipline_id":"5", "name":"8000m", "distance":"8000.00"},
        {"discipline_id":"4", "name":"2000m steeplechase", "distance":"2000.00"},
        {"discipline_id":"10", "name":"110m Hurdles (99.0cm)", "distance":"110.00", "hurdle_height":"0.9900"},
        {"discipline_id":"2", "name":"shot put (6kg)", "weight":"6000.00"},
        {"discipline_id":"2", "name":"Discus Throw (1.750kg)", "weight":"1750.00"},
        {"discipline_id":"2", "name":"hammer throw (6kg)", "weight":"6000.00"},
        {"discipline_id":"10", "name":"100m hurdles (76.2cm)", "distance":"100.00", "hurdle_height":"0.7620"},
        {"discipline_id":"5", "name":"9000m", "distance":"9000.00"},
        {"discipline_id":"5", "name":"6.5km", "distance":"6500.00"},
        {"discipline_id":"5", "name":"4500m", "distance":"4500.00"},
        {"discipline_id":"5", "name":"10.3km", "distance":"10300.00"},
        {"discipline_id":"5", "name":"8.3km", "distance":"8300.00"},
        {"discipline_id":"5", "name":"6.3km", "distance":"6300.00"},
        {"discipline_id":"5", "name":"4.3km", "distance":"4300.00"},
        {"discipline_id":"8", "name":"mixedrelay"},
        {"discipline_id":"5", "name":"9.53km", "distance":"9530.00"},
        {"discipline_id":"5", "name":"6.97km", "distance":"6970.00"},
        {"discipline_id":"8", "name":"9.47"},
        {"discipline_id":"5", "name":"6.105km", "distance":"6105.00"},
        {"discipline_id":"8", "name":"4.165km", "distance":"4165.00"},
        {"discipline_id":"8", "name":"7.91"},
        {"discipline_id":"8", "name":"3.36"},
        {"discipline_id":"2", "name":"javelin throw (oldmodel)"},
        {"discipline_id":"5", "name":"50km", "distance":"50000.00"},
        {"discipline_id":"4", "name":"1000m", "distance":"1000.00"},
        {"discipline_id":"7", "name":"4x200m relay", "distance":"800.00"},
        {"discipline_id":"5", "name":"9.7km", "distance":"9700.00"},
        {"discipline_id":"5", "name":"6.09km", "distance":"6090.00"},
        {"discipline_id":"5", "name":"10.5km", "distance":"10500.00"},
        {"discipline_id":"5", "name":"2.6km", "distance":"2600.00"},
        {"discipline_id":"5", "name":"7400m", "distance":"7400.00"},
        {"discipline_id":"5", "name":"5200m", "distance":"5200.00"},
        {"discipline_id":"5", "name":"20km", "distance":"20000.00"},
        {"discipline_id":"7", "name":"4x2laps"},
        {"discipline_id":"7", "name":"medleyrelay"},
        {"discipline_id":"7", "name":"4xlap"},
        {"discipline_id":"5", "name":"9.8km", "distance":"9800.00"},
        {"discipline_id":"5", "name":"6200m", "distance":"6200.00"},
        {"discipline_id":"5", "name":"3.7km", "distance":"3700.00"},
        {"discipline_id":"5", "name":"10.1km", "distance":"10100.00"},
        {"discipline_id":"5", "name":"6600m", "distance":"6600.00"},
        {"discipline_id":"5", "name":"4000m", "distance":"4000.00"},
        {"discipline_id":"10", "name":"110m hurdles (91.4cm)", "distance":"110.00", "hurdle_height":"0.9140"},
        {"discipline_id":"10", "name":"400m hurdles (84.0cm)", "distance":"400.00", "hurdle_height":"0.8400"},
        {"discipline_id":"2", "name":"shot put (5kg)", "weight":"5000.00"},
        {"discipline_id":"2", "name":"Discus Throw (1.500kg)", "weight":"1500.00"},
        {"discipline_id":"2", "name":"javelin throw (700g)", "weight":"700.00"},
        {"discipline_id":"5", "name":"9.84km", "distance":"9840.00"},
        {"discipline_id":"5", "name":"4.83km", "distance":"4830.00"},
        {"discipline_id":"5", "name":"half marathon", "distance":"21097.50"},
        {"discipline_id":"11", "name":"mountain running"},
        {"discipline_id":"5", "name":"10.7km", "distance":"10700.00"},
        {"discipline_id":"5", "name":"8.2km", "distance":"8200.00"},
        {"discipline_id":"5", "name":"6.7km", "distance":"6700.00"},
        {"discipline_id":"5", "name":"4200m", "distance":"4200.00"},
        {"discipline_id":"2", "name":"hammer throw (5kg)", "weight":"5000.00"},
        {"discipline_id":"5", "name":"9.997km", "distance":"9997.00"},
        {"discipline_id":"5", "name":"8.018km", "distance":"8018.00"},
        {"discipline_id":"5", "name":"6.039km", "distance":"6039.00"},
        {"discipline_id":"5", "name":"4.039km", "distance":"4039.00"},
        {"discipline_id":"4", "name":"600m", "distance":"600.00"},
        {"discipline_id":"6", "name":"Triathlon"},
        {"discipline_id":"3", "name":"300m", "distance":"300.00"},
        {"discipline_id":"5", "name":"15000m", "distance":"15000.00"},
        {"discipline_id":"2", "name":"javelin throw (500g)", "weight":"500.00"},
        {"discipline_id":"4", "name":"2000m", "distance":"2000.00"},
        {"discipline_id":"5", "name":"9600m", "distance":"9600.00"},
        {"discipline_id":"5", "name":"5600m", "distance":"5600.00"},
        {"discipline_id":"5", "name":"9.95 km", "distance":"9950.00"},
        {"discipline_id":"5", "name":"9.76 km", "distance":"9760.00"},
        {"discipline_id":"5", "name":"5500m", "distance":"5500.00"},
        {"discipline_id":"5", "name":"7.64 km", "distance":"7640.00"},
        {"discipline_id":"5", "name":"3.34 km", "distance":"3340.00"},
        {"discipline_id":"5", "name":"10.796 km", "distance":"10796.00"},
        {"discipline_id":"5", "name":"6.624 km", "distance":"6624.00"},
        {"discipline_id":"5", "name":"4.538 km", "distance":"4538.00"},
        {"discipline_id":"3", "name":"150m", "distance":"150.00"},
        {"discipline_id":"10", "name":"300m hurdles", "distance":"300.00"},
        {"discipline_id":"7", "name":"4 x 300m Relay", "distance":"1200.00"},
        {"discipline_id":"2", "name":"shot put (4kg)", "weight":"4000.00"},
        {"discipline_id":"2", "name":"Discus Throw (1.000kg)", "weight":"1000.00"},
        {"discipline_id":"2", "name":"shot put (3kg)", "weight":"3000.00"},
        {"discipline_id":"2", "name":"hammer throw (3kg)", "weight":"3000.00"},
        {"discipline_id":"3", "name":"250m", "distance":"250.00"},
        {"discipline_id":"5", "name":"9.41 km", "distance":"9410.00"},
        {"discipline_id":"5", "name":"6.25 km", "distance":"6250.00"},
        {"discipline_id":"5", "name":"4.37 km", "distance":"4370.00"},
        {"discipline_id":"5", "name":"8.1 km", "distance":"8100.00"},
        {"discipline_id":"5", "name":"6.24 km", "distance":"6240.00"},
        {"discipline_id":"5", "name":"9.9km", "distance":"9900.00"},
        {"discipline_id":"5", "name":"8.05km", "distance":"8050.00"},
        {"discipline_id":"5", "name":"6.03km", "distance":"6030.00"},
        {"discipline_id":"5", "name":"10,575 km", "distance":"10575.00"},
        {"discipline_id":"5", "name":"6,775 km", "distance":"6775.00"},
        {"discipline_id":"5", "name":"9.1 km", "distance":"9100.00"},
        {"discipline_id":"5", "name":"6400m", "distance":"6400.00"},
        {"discipline_id":"5", "name":"9.5 km", "distance":"9500.00"},
        {"discipline_id":"5", "name":"7600m", "distance":"7600.00"},
        {"discipline_id":"5", "name":"4600m", "distance":"4600.00"},
        {"discipline_id":"2", "name":"weight throw"},
        {"discipline_id":"3", "name":"500m", "distance":"500.00"},
        {"discipline_id":"5", "name":"2 miles, road", "distance":"3218.69"},
        {"discipline_id":"4", "name":"mile, road", "distance":"1609.34"},
        {"discipline_id":"5", "name":"10.01km", "distance":"10010.00"},
        {"discipline_id":"5", "name":"7.782km", "distance":"7782.00"},
        {"discipline_id":"5", "name":"6.085km", "distance":"6085.00"},
        {"discipline_id":"5", "name":"3.857km", "distance":"3857.00"},
        {"discipline_id":"5", "name":"6.65 km", "distance":"6650.00"},
        {"discipline_id":"5", "name":"10.117km", "distance":"10117.00"},
        {"discipline_id":"5", "name":"8.087km", "distance":"8087.00"},
        {"discipline_id":"5", "name":"5.947km", "distance":"5947.00"},
        {"discipline_id":"5", "name":"4.157km", "distance":"4157.00"},
        {"discipline_id":"5", "name":"5900m", "distance":"5900.00"},
        {"discipline_id":"10", "name":"60m hurdles (91.4cm)", "distance":"60.00", "hurdle_height":"0.9140"},
        {"discipline_id":"10", "name":"60m hurdles (76.2cm)", "distance":"60.00", "hurdle_height":"0.7620"},
        {"discipline_id":"5", "name":"30km", "distance":"30000.00"},
        {"discipline_id":"5", "name":"9.3 km", "distance":"9300.00"},
        {"discipline_id":"5", "name":"6.86 km", "distance":"6860.00"},
        {"discipline_id":"5", "name":"9.94km", "distance":"9940.00"},
        {"discipline_id":"5", "name":"7.97km", "distance":"7970.00"},
        {"discipline_id":"5", "name":"4.06km", "distance":"4060.00"},
        {"discipline_id":"5", "name":"6100m", "distance":"6100.00"},
        {"discipline_id":"10", "name":"60m hurdles (99cm)", "distance":"60.00", "hurdle_height":"0.9900"},
        {"discipline_id":"5", "name":"35 km", "distance":"35000.00"},
        {"discipline_id":"5", "name":"4800m", "distance":"4800.00"},
        {"discipline_id":"5", "name":"30000m", "distance":"30000.00"},
        {"discipline_id":"5", "name":"13km", "distance":"13000.00"},
        {"discipline_id":"5", "name":"5.725km", "distance":"5725.00"},
        {"discipline_id":"5", "name":"8.74km", "distance":"8740.00"},
        {"discipline_id":"5", "name":"6.49km", "distance":"6490.00"},
        {"discipline_id":"5", "name":"7500m", "distance":"7500.00"},
        {"discipline_id":"5", "name":"10.18km", "distance":"10180.00"},
        {"discipline_id":"5", "name":"8.23km", "distance":"8230.00"},
        {"discipline_id":"5", "name":"6.28km", "distance":"6280.00"},
        {"discipline_id":"5", "name":"4.18km", "distance":"4180.00"},
        {"discipline_id":"5", "name":"9.87km", "distance":"9870.00"},
        {"discipline_id":"5", "name":"8.17km", "distance":"8170.00"},
        {"discipline_id":"5", "name":"6.07km", "distance":"6070.00"},
        {"discipline_id":"5", "name":"3.97km", "distance":"3970.00"},
        {"discipline_id":"8", "name":""},
        {"discipline_id":"5", "name":"8.03km", "distance":"8030.00"},
        {"discipline_id":"5", "name":"5.975km", "distance":"5975.00"},
        {"discipline_id":"5", "name":"4100m", "distance":"4100.00"},
        {"discipline_id":"5", "name":"3.6km", "distance":"3600.00"},
        {"discipline_id":"7", "name":"4 x 4 laps"},
        {"discipline_id":"5", "name":"3.8km", "distance":"3800.00"},
        {"discipline_id":"7", "name":"4 x 800m Relay", "distance":"3200.00"},
        {"discipline_id":"5", "name":"1.5km", "distance":"1500.00"},
        {"discipline_id":"10", "name":"200m hurdles", "distance":"200.00"},
        {"discipline_id":"5", "name":"10 Mile", "distance":"16093.40"},
        {"discipline_id":"5", "name":"25KM", "distance":"25000.00"},
        {"discipline_id":"5", "name":"12KM", "distance":"12000.00"},
        {"discipline_id":"5", "name":"11KM", "distance":"11000.00"},
        {"discipline_id":"5", "name":"13.2KM", "distance":"13200.00"},
        {"discipline_id":"4", "name":"1500m STEEPLECHASE", "distance":"1500.00"},
        {"discipline_id":"11", "name":"B Race"},
        {"discipline_id":"11", "name":"HAET 2"},
        {"discipline_id":"11", "name":"HEAT 2"},
        {"discipline_id":"11", "name":"Group 2"},
        {"discipline_id":"5", "name":"100KM", "distance":"100000.00"},
        {"discipline_id":"11", "name":"QUALIFYING"},
        {"discipline_id":"5", "name":"13.3KM", "distance":"13300.00"},
        {"discipline_id":"5", "name":"12.3KM", "distance":"12300.00"},
        {"discipline_id":"5", "name":"4.7KM", "distance":"4700.00"},
        {"discipline_id":"7", "name":"1600 MEDLEY RELAY", "distance":"1600.00"},
        {"discipline_id":"11", "name":"Re-Run"},
        {"discipline_id":"7", "name":"4x110 YARDS RELAY", "distance":"402.34"},
        {"discipline_id":"5", "name":"7000m", "distance":"7000.00"},
        {"discipline_id":"5", "name":"7750m", "distance":"7750.00"},
        {"discipline_id":"5", "name":"7.3KM", "distance":"7300.00"},
        {"discipline_id":"5", "name":"11.2KM", "distance":"11200.00"},
        {"discipline_id":"5", "name":"11.5KM", "distance":"11500.00"},
        {"discipline_id":"5", "name":"11.75KM", "distance":"11750.00"},
        {"discipline_id":"11", "name":"RACE 2"},
        {"discipline_id":"3", "name":"440 YARDS RELAY", "distance":"402.34"},
        {"discipline_id":"5", "name":"1\u00bd MILES", "distance":"2414.02"},
        {"discipline_id":"11", "name":"FURTHER TRIAL"},
        {"discipline_id":"10", "name":"220 YARDS HURDLES", "distance":"201.17"},
        {"discipline_id":"11", "name":"Men"},
        {"discipline_id":"7", "name":"1 MILE MEDLEY RELAY", "distance":"1609.34"},
        {"discipline_id":"10", "name":"90 YARDS HURDLES", "distance":"82.30"},
        {"discipline_id":"11", "name":"Women"},
        {"discipline_id":"6", "name":"Octathlon"},
        {"discipline_id":"11", "name":"Long Race"},
        {"discipline_id":"11", "name":"Short Race"},
        {"discipline_id":"11", "name":"U20 Race"},
        {"discipline_id":"11", "name":"Road Relay"},
        {"discipline_id":"7", "name":"4x1500m relay", "distance":"6000.00"},
        {"discipline_id":"7", "name":"4x400m relay mixed", "distance":"1600.00"},
        {"discipline_id":"11", "name":"Senior Race"},
        {"discipline_id":"7", "name":"Distance Medley Relay"},
        {"discipline_id":"7", "name":"8x100m relay mixed", "distance":"800.00"},
        {"discipline_id":"5", "name":"20000m", "distance":"20000.00"},
        {"discipline_id":"3", "name":"200m Amputee", "distance":"200.00"},
        {"discipline_id":"3", "name":"400m Cereb. Palsy", "distance":"400.00"},
        {"discipline_id":"3", "name":"400m Blind", "distance":"400.00"},
        {"discipline_id":"3", "name":"200m Blind", "distance":"200.00"},
        {"discipline_id":"11", "name":"Decathlon J-110mH 1.067m", "distance":"110.00", "hurdle_height":"1.0670"},
        {"discipline_id":"11", "name":"heptathlon-100mh 76.2cm", "distance":"100.00", "hurdle_height":"0.7620"},
        {"discipline_id":"3", "name":"100m Blind", "distance":"100.00"},
        {"discipline_id":"3", "name":"100m Amputee", "distance":"100.00"},
        {"discipline_id":"11", "name":"One Hour"},
        {"discipline_id":"3", "name":"200m Visually Impaired", "distance":"200.00"},
        {"discipline_id":"4", "name":"800m t54", "distance":"800.00"},
        {"discipline_id":"3", "name":"400m t53", "distance":"400.00"},
        {"discipline_id":"7", "name":"Mixed Relay mixed"},
        {"discipline_id":"5", "name":"2.5Mile", "distance":"4023.35"},
        {"discipline_id":"7", "name":"4x110Y", "distance":"402.34"},
        {"discipline_id":"7", "name":"Sprint Medley Relay"},
        {"discipline_id":"10", "name":"330 Yards Hurdles", "distance":"301.75"},
        {"discipline_id":"5", "name":"3200m", "distance":"3200.00"},
        {"discipline_id":"4", "name":"1600m", "distance":"1600.00"},
        {"discipline_id":"5", "name":"3Mile", "distance":"4828.02"},
        {"discipline_id":"3", "name":"55m", "distance":"55.00"},
        {"discipline_id":"10", "name":"55m Hurdles", "distance":"55.00"},
        {"discipline_id":"5", "name":"2.xMile", "distance":"3218.68"},
        {"discipline_id":"3", "name":"45m", "distance":"45.00"},
        {"discipline_id":"7", "name":"4x51.5SHR"},
        {"discipline_id":"7", "name":"4x55SHR"},
        {"discipline_id":"7", "name":"4x60SHR"},
        {"discipline_id":"5", "name":"2600m", "distance":"2600.00"},
        {"discipline_id":"7", "name":"Sprint Medley Relay (800m)", "distance":"800.00"},
        {"discipline_id":"7", "name":"4x100SHR"},
        {"discipline_id":"7", "name":"4x110SHR"},
        {"discipline_id":"5", "name":"2500m", "distance":"2500.00"},
        {"discipline_id":"5", "name":"2400m", "distance":"2400.00"},
        {"discipline_id":"7", "name":"4xMile", "distance":"6437.36"},
        {"discipline_id":"7", "name":"4x100T"},
        {"discipline_id":"7", "name":"4x1600m", "distance":"6400.00"},
        {"discipline_id":"11", "name":"1.xMile", "distance":"1609.34"},
        {"discipline_id":"5", "name":"3500m", "distance":"3500.00"},
        {"discipline_id":"10", "name":"110H-39", "distance":"110.00"},
        {"discipline_id":"3", "name":"600 Yards", "distance":"548.64"},
        {"discipline_id":"5", "name":"2.1Mile", "distance":"3379.61"},
        {"discipline_id":"5", "name":"5Mile", "distance":"8046.70"},
        {"discipline_id":"3", "name":"60 Yards", "distance":"54.86"},
        {"discipline_id":"10", "name":"60 Yard Hurdles", "distance":"54.86"},
        {"discipline_id":"7", "name":"4x220Y", "distance":"804.67"},
        {"discipline_id":"7", "name":"4x880Y", "distance":"3218.69"},
        {"discipline_id":"5", "name":"4Mile", "distance":"6437.36"},
        {"discipline_id":"6", "name":"Decathlon (Variant)"},
        {"discipline_id":"4", "name":"1000 Yards", "distance":"914.40"},
        {"discipline_id":"7", "name":"4x800Y", "distance":"2926.08"},
        {"discipline_id":"7", "name":"Sprint Medley Relay (1200m)", "distance":"1200.00"},
        {"discipline_id":"11", "name":"Shot Put - Wheel Chair"},
        {"discipline_id":"4", "name":"1800m", "distance":"1800.00"},
        {"discipline_id":"3", "name":"300 Yards", "distance":"274.32"},
        {"discipline_id":"5", "name":"3.xMile", "distance":"4828.02"},
        {"discipline_id":"7", "name":"4x200Y", "distance":"731.52"},
        {"discipline_id":"5", "name":"5150m", "distance":"5150.00"},
        {"discipline_id":"5", "name":"5250m", "distance":"5250.00"},
        {"discipline_id":"7", "name":"4x160m", "distance":"640.00"},
        {"discipline_id":"4", "name":"2800m", "distance":"2800.00"},
        {"discipline_id":"5", "name":"50000m", "distance":"50000.00"},
        {"discipline_id":"7", "name":"4 x 100 Hurdles", "distance":"400.00"},
        {"discipline_id":"7", "name":"4x110m Hurdles", "distance":"440.00"},
        {"discipline_id":"7", "name":"4x440Y", "distance":"1609.34"},
        {"discipline_id":"10", "name":"75m Hurdles", "distance":"75.00"},
        {"discipline_id":"10", "name":"50 Yards Hurdles", "distance":"45.72"},
        {"discipline_id":"7", "name":"4x100Y", "distance":"365.76"},
        {"discipline_id":"7", "name":"4x400 Yards Relay", "distance":"1463.04"},
        {"discipline_id":"7", "name":"3x55SHR"},
        {"discipline_id":"10", "name":"45 Yards Hurdles", "distance":"41.15"},
        {"discipline_id":"7", "name":"4x140Y", "distance":"512.06"},
        {"discipline_id":"3", "name":"240 Yards", "distance":"219.46"},
        {"discipline_id":"7", "name":"4x210Y", "distance":"768.10"},
        {"discipline_id":"3", "name":"150 Yards", "distance":"137.16"},
        {"discipline_id":"3", "name":"40 Yards", "distance":"36.58"},
        {"discipline_id":"11", "name":"TurboJav"},
        {"discipline_id":"11", "name":"Shot Put (2.720kg)", "weight":"2720.00"},
        {"discipline_id":"11", "name":"javelin throw (600g)", "weight":"600.00"},
        {"discipline_id":"3", "name":"55"},
        {"discipline_id":"10", "name":"400H-30", "distance":"400.00", "hurdle_height":"0.7620"},
        {"discipline_id":"4", "name":"1200m", "distance":"1200.00"},
        {"discipline_id":"7", "name":"Sprint Medley Relay (1000m)", "distance":"1000.00"},
        {"discipline_id":"10", "name":"65m Hurdles", "distance":"65.00"},
        {"discipline_id":"5", "name":"2700m", "distance":"2700.00"},
        {"discipline_id":"10", "name":"100H-30", "distance":"110.00", "hurdle_height":"0.7620"},
        {"discipline_id":"2", "name":"Weight Throw (35)"},
        {"discipline_id":"11", "name":"Discus Throw - Wheel Chair"},
        {"discipline_id":"7", "name":"4x3200m", "distance":"12800.00"},
        {"discipline_id":"3", "name":"55 Hurdles", "distance":"55.00"},
        {"discipline_id":"7", "name":"4 X 1600 Relay"},
        {"discipline_id":"7", "name":"Shuttle Hurdle Relay"},
        {"discipline_id":"3", "name":"110M ", "distance":"110.00"},
        {"discipline_id":"7", "name":"4 X 1500 Relay"},
        {"discipline_id":"7", "name":"4 X 1 Mile Relay", "distance":"6437.38"},
        {"discipline_id":"7", "name":"4 X 880 Yard Relay", "distance":"3218.69"},
        {"discipline_id":"7", "name":"4X100 Yard Relay", "distance":"365.76"},
        {"discipline_id":"3", "name":"80M ", "distance":"80.00"},
        {"discipline_id":"7", "name":"4 X 145 Relay"},
        {"discipline_id":"5", "name":"2792m", "distance":"2792.00"},
        {"discipline_id":"7", "name":"4 X 220 Yard Relay", "distance":"804.67"},
        {"discipline_id":"4", "name":"548m", "distance":"548.00"},
        {"discipline_id":"3", "name":"195m", "distance":"195.00"},
        {"discipline_id":"3", "name":"400 Yards", "distance":"365.76"},
        {"discipline_id":"5", "name":"5000 Yards", "distance":"4572.00"},
        {"discipline_id":"5", "name":"3000 Yards", "distance":"2743.20"},
        {"discipline_id":"5", "name":"3200 Steeplechase", "distance":"3200.00"},
        {"discipline_id":"3", "name":"494m", "distance":"494.00"},
        {"discipline_id":"7", "name":"4 X 320 Relay"},
        {"discipline_id":"3", "name":"40m", "distance":"40.00"},
        {"discipline_id":"3", "name":"4,400 Yard", "distance":"4023.36"},
        {"discipline_id":"5", "name":"2840m", "distance":"2840.00"},
        {"discipline_id":"3", "name":"35m", "distance":"35.00"},
        {"discipline_id":"4", "name":"800 Yards", "distance":"731.52"},
        {"discipline_id":"5", "name":"2600 Steeplechase", "distance":"2600.00"},
        {"discipline_id":"3", "name":"30m", "distance":"30.00"},
        {"discipline_id":"4", "name":"1609m", "distance":"1609.00"},
        {"discipline_id":"4", "name":"1000m Steeplechase", "distance":"1000.00"},
        {"discipline_id":"3", "name":"102m", "distance":"102.00"},
        {"discipline_id":"3", "name":"101m", "distance":"101.00"},
        {"discipline_id":"4", "name":"1501m", "distance":"1501.00"},
        {"discipline_id":"3", "name":"201m", "distance":"201.00"},
        {"discipline_id":"4", "name":"1500 Yards", "distance":"1371.60"},
        {"discipline_id":"3", "name":"1m", "distance":"1.00"},
        {"discipline_id":"7", "name":"4 X 1609 Relay"},
        {"discipline_id":"3", "name":"70m Hurdles", "distance":"70.00"},
        {"discipline_id":"1", "name":"4.97 Mile", "distance":"7998.42"},
        {"discipline_id":"1", "name":"4.98 Mile", "distance":"8014.51"},
        {"discipline_id":"1", "name":"9200m", "distance":"9200.00"},
        {"discipline_id":"1", "name":"7250m", "distance":"7250.00"},
        {"discipline_id":"1", "name":"5800m", "distance":"5800.00"},
        {"discipline_id":"1", "name":"6.437K", "distance":"6437.00"},
        {"discipline_id":"1", "name":"7900m", "distance":"7900.00"},
        {"discipline_id":"1", "name":"8400m", "distance":"8400.00"},
        {"discipline_id":"1", "name":"4721m", "distance":"4721.00"},
        {"discipline_id":"1", "name":"4163m", "distance":"4163.00"},
        {"discipline_id":"1", "name":"6123m", "distance":"6123.00"},
        {"discipline_id":"1", "name":"4523m", "distance":"4523.00"},
        {"discipline_id":"1", "name":"6195m", "distance":"6195.00"},
        {"discipline_id":"1", "name":"4965M ", "distance":"4965.00"},
        {"discipline_id":"1", "name":"3218m", "distance":"3218.00"},
        {"discipline_id":"1", "name":"2.48 Mile", "distance":"3991.16"},
        {"discipline_id":"1", "name":"5120m", "distance":"5120.00"},
        {"discipline_id":"1", "name":"5.83K", "distance":"5830.00"},
        {"discipline_id":"1", "name":"6630m", "distance":"6630.00"},
        {"discipline_id":"1", "name":"7200m", "distance":"7200.00"},
        {"discipline_id":"1", "name":"4.81 Mile", "distance":"7740.93"},
        {"discipline_id":"1", "name":"4850m", "distance":"4850.00"},
        {"discipline_id":"1", "name":"195 Mile", "distance":"313821.30"},
        {"discipline_id":"1", "name":"4300m", "distance":"4300.00"},
        {"discipline_id":"1", "name":"3.9 Mile", "distance":"6276.43"},
        {"discipline_id":"1", "name":"4.25 Mile", "distance":"6839.70"},
        {"discipline_id":"1", "name":"6327m", "distance":"6327.00"},
        {"discipline_id":"1", "name":"4661m", "distance":"4661.00"},
        {"discipline_id":"1", "name":"4750m", "distance":"4750.00"},
        {"discipline_id":"1", "name":"5.8K", "distance":"5800.00"},
        {"discipline_id":"1", "name":"3.72 Mile", "distance":"5986.74"},
        {"discipline_id":"1", "name":"6368m", "distance":"6368.00"},
        {"discipline_id":"1", "name":"8 Mile", "distance":"12874.72"},
        {"discipline_id":"1", "name":"4380m", "distance":"4380.00"},
        {"discipline_id":"1", "name":"4.17K", "distance":"4170.00"},
        {"discipline_id":"1", "name":"8.8K", "distance":"8800.00"},
        {"discipline_id":"1", "name":"3.12 Mile", "distance":"5021.14"},
        {"discipline_id":"1", "name":"6437m", "distance":"6437.00"},
        {"discipline_id":"1", "name":"4828m", "distance":"4828.00"},
        {"discipline_id":"1", "name":"7100m", "distance":"7100.00"},
        {"discipline_id":"1", "name":"5,000 Mile", "distance":"8046.70"},
        {"discipline_id":"1", "name":"7710m", "distance":"7710.00"},
        {"discipline_id":"1", "name":"4010m", "distance":"4010.00"},
        {"discipline_id":"1", "name":"7690m", "distance":"7690.00"},
        {"discipline_id":"1", "name":"2.735K", "distance":"2735.00"},
        {"discipline_id":"1", "name":"2.7K", "distance":"2700.00"},
        {"discipline_id":"1", "name":"7800m", "distance":"7800.00"},
        {"discipline_id":"1", "name":"8035M ", "distance":"8035.00"},
        {"discipline_id":"1", "name":"5.008K", "distance":"5008.00"},
        {"discipline_id":"1", "name":"4.828K", "distance":"4828.00"},
        {"discipline_id":"1", "name":"4.94 Miles", "distance":"7950.16"},
        {"discipline_id":"1", "name":"2.95K", "distance":"2950.00"},
        {"discipline_id":"1", "name":"5030M ", "distance":"5030.00"},
        {"discipline_id":"1", "name":"3660m", "distance":"3660.00"},
        {"discipline_id":"1", "name":"4730m", "distance":"4730.00"},
        {"discipline_id":"1", "name":"5.23 Mile", "distance":"8416.85"},
        {"discipline_id":"1", "name":"3.02 Mile", "distance":"4860.21"},
        {"discipline_id":"1", "name":"3.11 Mile", "distance":"5005.05"},
        {"discipline_id":"1", "name":"3.03 Mile", "distance":"4876.30"},
        {"discipline_id":"1", "name":"5.25K", "distance":"5250.00"},
        {"discipline_id":"1", "name":"6040m", "distance":"6040.00"},
        {"discipline_id":"1", "name":"7993m", "distance":"7993.00"},
        {"discipline_id":"1", "name":"5.01 Mile", "distance":"8062.79"},
        {"discipline_id":"1", "name":"3.71 Mile", "distance":"5970.65"},
        {"discipline_id":"1", "name":"3.1K", "distance":"3100.00"},
        {"discipline_id":"1", "name":"4.34K", "distance":"4340.00"},
        {"discipline_id":"1", "name":"8.033K", "distance":"8033.00"},
        {"discipline_id":"1", "name":"4.94K", "distance":"4940.00"},
        {"discipline_id":"1", "name":"7950m", "distance":"7950.00"},
        {"discipline_id":"1", "name":"4.97K", "distance":"4970.00"},
        {"discipline_id":"1", "name":"7.96K", "distance":"7960.00"},
        {"discipline_id":"1", "name":"8369m", "distance":"8369.00"},
        {"discipline_id":"1", "name":"4.61K", "distance":"4610.00"},
        {"discipline_id":"1", "name":"2.95 Mile", "distance":"4747.55"},
        {"discipline_id":"1", "name":"6.44K", "distance":"6440.00"},
        {"discipline_id":"1", "name":"3.055K", "distance":"3055.00"},
        {"discipline_id":"1", "name":"3.04 Mile", "distance":"4892.39"},
        {"discipline_id":"1", "name":"6.438K", "distance":"6438.00"},
        {"discipline_id":"1", "name":"7850m", "distance":"7850.00"},
        {"discipline_id":"1", "name":"3219m", "distance":"3219.00"},
        {"discipline_id":"1", "name":"8.075K", "distance":"8075.00"},
        {"discipline_id":"1", "name":"4.971K", "distance":"4971.00"},
        {"discipline_id":"1", "name":"5.95K", "distance":"5950.00"},
        {"discipline_id":"1", "name":"3.05 Mile", "distance":"4908.49"},
        {"discipline_id":"1", "name":"4.98K", "distance":"4980.00"},
        {"discipline_id":"1", "name":"6.05K", "distance":"6050.00"},
        {"discipline_id":"1", "name":"7.985K", "distance":"7985.00"},
        {"discipline_id":"1", "name":"3.4K", "distance":"3400.00"},
        {"discipline_id":"1", "name":"2.253K", "distance":"2253.00"},
        {"discipline_id":"1", "name":"3.1  Mile", "distance":"4988.95"},
        {"discipline_id":"1", "name":"4.91K", "distance":"4910.00"},
        {"discipline_id":"1", "name":"8.085K", "distance":"8085.00"},
        {"discipline_id":"1", "name":"4.975K", "distance":"4975.00"},
        {"discipline_id":"1", "name":"5920m", "distance":"5920.00"},
        {"discipline_id":"1", "name":"4.19 Mile", "distance":"6743.13"},
        {"discipline_id":"1", "name":"5870m", "distance":"5870.00"},
        {"discipline_id":"1", "name":"1K", "distance":"1000.00"},
        {"discipline_id":"1", "name":"9725m", "distance":"9725.00"},
        {"discipline_id":"1", "name":"5.848K", "distance":"5848.00"},
        {"discipline_id":"1", "name":"3.219K", "distance":"3219.00"},
        {"discipline_id":"1", "name":"5.93K", "distance":"5930.00"},
        {"discipline_id":"1", "name":"4.96K", "distance":"4960.00"},
        {"discipline_id":"1", "name":"5.985K", "distance":"5985.00"},
        {"discipline_id":"1", "name":"4.8K", "distance":"4800.00"},
        {"discipline_id":"1", "name":"3800m", "distance":"3800.00"},
        {"discipline_id":"1", "name":"6387m", "distance":"6387.00"},
        {"discipline_id":"1", "name":"3.72823 Miles", "distance":"6000.00"},
        {"discipline_id":"1", "name":"2.49 Mile", "distance":"4007.26"},
        {"discipline_id":"1", "name":"5.872K", "distance":"5872.00"},
        {"discipline_id":"1", "name":"5.875K", "distance":"5875.00"},
        {"discipline_id":"1", "name":"9.981K", "distance":"9981.00"},
        {"discipline_id":"5", "name":"3.74 Miles", "distance":"6018.95"},
        {"discipline_id":"1", "name":"6.2 Mile", "distance":"9977.91"},
        {"discipline_id":"1", "name":"4980M ", "distance":"4980.00"},
        {"discipline_id":"1", "name":"5.15 Mile", "distance":"8288.10"},
        {"discipline_id":"1", "name":"5848m", "distance":"5848.00"},
        {"discipline_id":"5", "name":"3.94 Miles", "distance":"6340.82"},
        {"discipline_id":"5", "name":"4.96 Miles", "distance":"7982.35"}]

        for event in events:
            discipline_id = event.pop('discipline_id')
            discipline = athletics.models.Discipline.objects.get(id=discipline_id)
            distance = event.pop('distance', None)
            weight = event.pop('weight', None)
            hurdle_height = event.pop("hurdle_height", None)
            name = event['name']
            slug = slugify(name)
            try:
                instance = athletics.models.Event.objects.get(discipline=discipline, name=name, slug=slug)
            except Exception:
                instance = athletics.models.Event(discipline=discipline, name=name, slug=slug, description='', created_by=superuser_identity)
                instance.save()

            if distance:
                try:
                    measure = athletics.models.EventDistance.objects.get(event=instance, distance=distance)
                except Exception:
                    unit = utility.models.Unit.objects.get(name='Meter')
                    measure = athletics.models.EventDistance(event=instance, distance=distance, distance_unit=unit, created_by=superuser_identity)
                    measure.save()
            elif weight:
                try:
                    measure = athletics.models.EventWeight.objects.get(event=instance, weight=weight)
                except Exception:
                    unit = utility.models.Unit.objects.get(name='Kilogram')
                    measure = athletics.models.EventWeight(event=instance, weight=weight, weight_unit=unit, created_by=superuser_identity)
                    measure.save()
            elif hurdle_height:
                try:
                    measure = athletics.models.EventHurdles(event=instance, height=hurdle_height)
                except Exception:
                    unit = utility.models.Unit.objects.get(name='Meter')
                    measure = athletics.models.EventHurdles(event=instance, height=hurdle_height, height_unit=unit, created_by=superuser_identity)
                    measure.save()


    def add_annotation_types(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

    def add_performance_states(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        performance_states = [
            {"code":"FINISH", "name":"Finished"},
            {"code":"ND", "name":"No Distance"},
            {"code":"FOUL", "name":"FOUL"},
            {"code":"PASS", "name":"PASS"},
            {"code":"PPP", "name":"PPP"},
            {"code":"DNF", "name":"Did Not Finish"},
            {"code":"NH", "name":"No Height"},
            {"code":"FS", "name":"False Start"},
            {"code":"DQ", "name":"Disqualified"},
            {"code":"-", "name":"-"},
            {"code":"DNS", "name":"Did Not Start"},
            {"code":"NT", "name":"No Time (either not available or not known)"},
            {"code":"TP", "name":""},
            {"code":"NP", "name":""},
            {"code":"SCR", "name":"Scratch"},
            {"code":"DNC", "name":"Did Not Compete"},
            {"code":"NM", "name":"No Mark"},
            {"code":"PB", "name":"Personal Best"},
            {"code":"SB", "name":"Season Best"}
        ]

        for state in performance_states:
            code = state['code']
            name = state['name']
            try:
                instance = athletics.models.PerformanceState.objects.get(code=code, name=name)
            except Exception:
                instance = athletics.models.PerformanceState(code=code, name=name, description='', created_by=superuser_identity)
                instance.save()

    def add_environments(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        environments = ['Indoor', 'Outdoor']

        for name in environments:
            try:
                environment = athletics.models.Environment.objects.get(name=name)
            except Exception:
                environment = athletics.models.Environment(name=name, description='', created_by=superuser_identity)
                environment.save()


    def add_legitimacies(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        data = [{"name":"Verified", "description":"The item was verified by the governing organization to be legitimate"},
        {"name":"Statistical Anomaly", "description":"Based on other items, the item is statistically unlikely"},
        {"name":"Beyond Lower Bound", "description":"The item value is better than the current verified world record"}]

        for item in data:
            try:
                instance = athletics.models.Legitimacies.objects.get(**item)
            except Exception:
                instance = athletics.models.Legitimacies(**item, created_by=superuser_identity)
                instance.save()

    def add_modes(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        modes = ['Run', 'Walk', 'Wheel chair', 'Swim', 'Bike']

        for name in modes:
            try:
                instance = athletics.models.Mode.objects.get(name=name)
            except Exception:
                instance = athletics.models.Mode(name=name, description='', created_by=superuser_identity)
                instance.save()


    def add_meet_type(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        meet_types = ['Cross Country', 'Track & Field', 'Road Race']
        for name in meet_types:
            try:
                instance = athletics.models.MeetType.objects.get(name=name)
            except Exception:
                instance = athletics.models.MeetType(name=name, created_by=superuser_identity)
                instance.save()


    def add_social_class(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)
        data = [{
            'name': 'Freshman',
            'code': 'FR',
            'aliases': ['FR-1', 'FR', 'FR.', '1', 'Freshman']
            },
            {
                'name': 'Sophomore',
                'code': 'SO',
                'aliases': ['SO-2', 'FR', 'FR.', '2', 'Sophomore']
            },
            {
                'name': 'Junior',
                'code': 'JR',
                'aliases': ['JR-3', 'JR', 'JR.', '3', 'Junior']
            },
            {
                'name': 'Senior',
                'code': 'SR',
                'aliases': ['SR-4', 'SR', 'SR.', '4', 'Senior']
            },
        ]
        for item in data:
            aliases = item.pop('aliases', [])
            try:
                instance = athletics.models.SocialClass.objects.get(**item)
            except Exception:
                instance = athletics.models.SocialClass(**item, created_by=superuser_identity)
                instance.save()

            for alias in aliases:
                try:
                    alias_instance = athletics.models.SocialClassAlias.objects.get(social_class=instance, value=alias)
                except Exception:
                    alias_instance = athletics.models.SocialClassAlias(social_class=instance, value=alias, created_by=superuser_identity)
                    alias_instance.save()


    def add_seed_methods(apps, schema_editor):
        pass

    def add_strategies(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        strategies = ['Positive', 'Negative', 'Even', 'Sit and Kick', 'Oscillating']
        for name in strategies:
            try:
                instance = athletics.models.Strategy.objects.get(name=name)
            except Exception:
                instance = athletics.models.Strategy(name=name, description='', created_by=superuser_identity)
                instance.save()

    def add_tiers(apps, schema_editor):
        superusers = User.objects.filter(is_superuser=True).all()
        superuser = superusers[0]
        superuser_identity = identity.models.Identity.objects.get(user_id=superuser.id)

        tiers = ['Qualifications', 'Quarterfinals', 'Semifinals', 'Finals']
        levels = [3, 2, 1]
        for name, level in zip(tiers, levels):
            try:
                instance = athletics.models.Tier.objects.get(name=name, level=level)
            except Exception:
                instance = athletics.models.Tier(name=name, level=level, created_by=superuser_identity)
                instance.save()

    operations = [
        migrations.RunPython(add_sport_types),
        migrations.RunPython(add_sports),
        migrations.RunPython(add_tiers),
        migrations.RunPython(add_strategies),
        migrations.RunPython(add_meet_type),
        migrations.RunPython(add_environments),
        migrations.RunPython(add_performance_states),
        migrations.RunPython(add_disciplines),
        migrations.RunPython(add_events),
        migrations.RunPython(add_modes),
        migrations.RunPython(add_legitimacies),
        migrations.RunPython(add_social_class),
        migrations.RunPython(competition_type)
    ]
