# Generated by Django 2.2.11 on 2020-07-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
        ('athletics', '0001_initial'),
        ('geography', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingsystem',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='timingsystem_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='timingsystem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timingsystem_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='tier',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tier_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='tier',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tier_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='surface',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_surfaces', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='surface',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_surfaces', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='substances',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='substances_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='substances',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='substances_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategy_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategy_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingvenue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingvenue_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingvenue',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingvenue_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelaysplit',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingrelaysplit_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelaysplit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingrelaysplit_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelaysplit',
            name='staging_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingrelaysplit',
            name='staging_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingPerformance'),
        ),
        migrations.AddField(
            model_name='stagingrelayperformanceparticipants',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_staging_relay_participants', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelayperformanceparticipants',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_staging_relay_participants', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelayperformanceparticipants',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staging_relay_member_performances', to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingrelayperformanceparticipants',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='stagingrelayperformanceparticipants',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingrelaymembers',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingrelaymembers_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelaymembers',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingrelaymembers_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingrelaymembers',
            name='staging_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staging_relay_memberships', to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingrelaymembers',
            name='staging_relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staging_relays', to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingperformance_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingperformance_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='legitimacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Legitimacies'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='social_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.SocialClass'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='staging_heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingHeat'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.PerformanceState'),
        ),
        migrations.AddField(
            model_name='stagingperformance',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Strategy'),
        ),
        migrations.AddField(
            model_name='stagingmeetinstance',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingmeetinstance_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingmeetinstance',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingmeetinstance_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingmeetinstance',
            name='staging_meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingMeet'),
        ),
        migrations.AddField(
            model_name='stagingmeetinstance',
            name='staging_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingVenue'),
        ),
        migrations.AddField(
            model_name='stagingmeet',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingmeet_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingmeet',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Environment'),
        ),
        migrations.AddField(
            model_name='stagingmeet',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingmeet_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingmeet',
            name='meet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.MeetType'),
        ),
        migrations.AddField(
            model_name='stagingheat',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingheat_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingheat',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingheat_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingheat',
            name='staging_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='stagingheat',
            name='staging_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Tier'),
        ),
        migrations.AddField(
            model_name='stagingentity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingentity_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingentity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.EntityType'),
        ),
        migrations.AddField(
            model_name='stagingentity',
            name='knowledge_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.KnowledgeGraph'),
        ),
        migrations.AddField(
            model_name='stagingentity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingentity_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingcompetition_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staging_competition', to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingcompetition_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Mode'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='staging_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Division'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='staging_meet_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingMeetInstance'),
        ),
        migrations.AddField(
            model_name='stagingcompetition',
            name='subevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staging_subcompetition', to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='stagingattemptthreshold',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingAttempt'),
        ),
        migrations.AddField(
            model_name='stagingattemptthreshold',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattemptthreshold_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattemptthreshold',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattemptthreshold_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattemptsequential',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingAttempt'),
        ),
        migrations.AddField(
            model_name='stagingattemptsequential',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattemptsequential_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattemptsequential',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattemptsequential_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattempt',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattempt_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattempt',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.StagingIdentity'),
        ),
        migrations.AddField(
            model_name='stagingattempt',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stagingattempt_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='stagingattempt',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.StagingPerformance'),
        ),
        migrations.AddField(
            model_name='stagingattempt',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.PerformanceState'),
        ),
        migrations.AddField(
            model_name='sporttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sporttype_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sporttype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sporttype_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sport',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sport_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sport',
            name='knowledge_graph',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utility.KnowledgeGraph'),
        ),
        migrations.AddField(
            model_name='sport',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sport_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sport',
            name='scoring_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.SportType'),
        ),
        migrations.AddField(
            model_name='sponsorshipcompetition',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='sponsorshipcompetition',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsorshipcompetition_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipcompetition',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsorshipcompetition_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipcompetition',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipathlete',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsorshipathlete_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipathlete',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsors', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipathlete',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsorshipathlete_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sponsorshipathlete',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsored_athletes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='split',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='split_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='split',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='split_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='split',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='socialclassalias',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_social_class_aliases', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='socialclassalias',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_social_class_aliases', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='socialclassalias',
            name='social_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.SocialClass'),
        ),
        migrations.AddField(
            model_name='socialclass',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialclass_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='socialclass',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialclass_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seriesmeet',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seriesmeet_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seriesmeet',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seriesmeet_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seriesmeet',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Meet'),
        ),
        migrations.AddField(
            model_name='seriesmeet',
            name='series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Series'),
        ),
        migrations.AddField(
            model_name='serieshierarchy',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_series', to='athletics.Series'),
        ),
        migrations.AddField(
            model_name='serieshierarchy',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='serieshierarchy_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='serieshierarchy',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='serieshierarchy_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='serieshierarchy',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_series', to='athletics.Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='series',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seedmethod',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seedmethod_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seedmethod',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seedmethod_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seed',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='seed',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seed_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seed',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seed',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seed_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.SeedMethod'),
        ),
        migrations.AddField(
            model_name='scoring',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_scorings', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='scoring',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_scorings', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sanctions',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sanctions_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sanctions',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sanctions',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sanctions_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='sanctions',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Substances'),
        ),
        migrations.AddField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='rule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewflag_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewflag_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Review'),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Language'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='review',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaysplit',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaysplit_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaysplit',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaysplit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaysplit_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaysplit',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='relayperformanceparticipant',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_relay_participant_performance', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relayperformanceparticipant',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_relay_participant_performance', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relayperformanceparticipant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relay_memberships', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relayperformanceparticipant',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='relayperformanceparticipant',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaymember',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaymember_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaymember',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relays', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaymember',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaymember_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='relaymember',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relay_members', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performancestate',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='performancestate_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performancestate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performancestate_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performancesimilarity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='performancesimilarity_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performancesimilarity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performancesimilarity_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performancesimilarity',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performancesimilarity_other', to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='performancesimilarity',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='performanceannotation',
            name='annotation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.AnnotationType'),
        ),
        migrations.AddField(
            model_name='performanceannotation',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='performanceannotation_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performanceannotation',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performanceannotation_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performanceannotation',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='performanceannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performanceagegroup',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_performance_age_groups', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performanceagegroup',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_performance_age_groups', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performanceagegroup',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='performance',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='performance_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performance',
            name='field_of_play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.FieldOfPlay'),
        ),
        migrations.AddField(
            model_name='performance',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Heat'),
        ),
        migrations.AddField(
            model_name='performance',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performance',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performance_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performance',
            name='legitimacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Legitimacies'),
        ),
        migrations.AddField(
            model_name='performance',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Mode'),
        ),
        migrations.AddField(
            model_name='performance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_performances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='performance',
            name='social_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.SocialClass'),
        ),
        migrations.AddField(
            model_name='performance',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.PerformanceState'),
        ),
        migrations.AddField(
            model_name='performance',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Strategy'),
        ),
        migrations.AddField(
            model_name='mode',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_modes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='mode',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_modes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meettype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_meet_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meettype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_meet_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstancereview',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_meet_instance_reviews', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstancereview',
            name='last_modified_by',
            field=models.ForeignKey(db_column='last_modified_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_meet_instance_reviews', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstancereview',
            name='meet_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.MeetInstance'),
        ),
        migrations.AddField(
            model_name='meetinstancereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Review'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_meet_instances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_meet_instances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Meet'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organized_meet_instances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='timing_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.TimingSystem'),
        ),
        migrations.AddField(
            model_name='meetinstance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Venue'),
        ),
        migrations.AddField(
            model_name='meet',
            name='categories',
            field=models.ManyToManyField(through='athletics.CategoryMeet', to='athletics.Category'),
        ),
        migrations.AddField(
            model_name='meet',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_meets', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meet',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Division'),
        ),
        migrations.AddField(
            model_name='meet',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Environment'),
        ),
        migrations.AddField(
            model_name='meet',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_meets', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='meet',
            name='meet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.MeetType'),
        ),
        migrations.AddField(
            model_name='meet',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='legitimacies',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_legitimacies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='legitimacies',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_legitimacies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatsimilarity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_heat_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatsimilarity',
            name='heat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_heats', to='athletics.Heat'),
        ),
        migrations.AddField(
            model_name='heatsimilarity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_heat_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatsimilarity',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_similar_heats', to='athletics.Heat'),
        ),
        migrations.AddField(
            model_name='heatclusteringassignments',
            name='clustering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.HeatClustering'),
        ),
        migrations.AddField(
            model_name='heatclusteringassignments',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_heat_clustering_assignments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatclusteringassignments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_heat_clustering_assignments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatclusteringassignments',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='heatclusteringassignments',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Split'),
        ),
        migrations.AddField(
            model_name='heatclustering',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_heat_clusterings', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heatclustering',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Heat'),
        ),
        migrations.AddField(
            model_name='heatclustering',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_heat_clusterings', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heat',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='heat',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_heats', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heat',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_heats', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='heat',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Tier'),
        ),
        migrations.AddField(
            model_name='fieldofplay',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_fields_of_play', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='fieldofplay',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_fields_of_play', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='fieldofplay',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Sport'),
        ),
        migrations.AddField(
            model_name='fieldofplay',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_of_play', to='geography.Venue'),
        ),
        migrations.AddField(
            model_name='eventweight',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_event_weights', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='eventweight',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='eventweight',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_event_weights', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='eventweight',
            name='weight_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='eventhurdles',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_event_hurdles', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='eventhurdles',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='eventhurdles',
            name='height_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='eventhurdles',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_event_hurdles', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_event_distances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='distance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_event_distances', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_events', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='event',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Discipline'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_events', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='environment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_environments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='environment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_environments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='division',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_divisions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='division',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_divisions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='division',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='disqualification',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_disqualifications', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='disqualification',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_disqualifications', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='disqualification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_disciplines', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_disciplines', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Sport'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_course_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_course_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursesurface',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Course'),
        ),
        migrations.AddField(
            model_name='coursesurface',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_course_surfaces', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursesurface',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_course_surfaces', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursesurface',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Surface'),
        ),
        migrations.AddField(
            model_name='coursesimilarity',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_similarities', to='athletics.Course'),
        ),
        migrations.AddField(
            model_name='coursesimilarity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_course_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursesimilarity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_course_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursesimilarity',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_course_similarities', to='athletics.Course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_course_grades', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_course_grades', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.CourseType'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_courses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.FieldOfPlay'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_courses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='course',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Surface'),
        ),
        migrations.AddField(
            model_name='competitionweight',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionweight',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_weight', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionweight',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_weight', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionweight',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionsimilarity',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_competitions', to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionsimilarity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionsimilarity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_similarities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionsimilarity',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_similar_competitions', to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionracehurdles',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionracehurdles',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_race_hurdles', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionracehurdles',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_race_hurdles', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionracehurdles',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='competitionrace',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionrace',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_races', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionrace',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_races', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionrace',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Mode'),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Competition'),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competition_events', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='competitionevent',
            name='subevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competition_events', to='athletics.Event'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.CompetitionType'),
        ),
        migrations.AddField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_competitions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Division'),
        ),
        migrations.AddField(
            model_name='competition',
            name='field_of_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.FieldOfPlay'),
        ),
        migrations.AddField(
            model_name='competition',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_competitions', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='meet_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.MeetInstance'),
        ),
        migrations.AddField(
            model_name='competition',
            name='scoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Scoring'),
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Sport'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_comments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged_by',
            field=models.ForeignKey(blank=True, db_column='flagged_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged_comments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_comments', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Comment'),
        ),
        migrations.AddField(
            model_name='coach',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coaches', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='athletes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coach',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_coaches', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_coaches', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='categorymeet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Category'),
        ),
        migrations.AddField(
            model_name='categorymeet',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_category_meets', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='categorymeet',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_category_meets', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='categorymeet',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Meet'),
        ),
        migrations.AddField(
            model_name='categoryhierarchy',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='athletics.Category'),
        ),
        migrations.AddField(
            model_name='categoryhierarchy',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_category_hierarchies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='categoryhierarchy',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_category_hierarchies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='categoryhierarchy',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='athletics.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_categories', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_categories', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attemptthreshold',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Attempt'),
        ),
        migrations.AddField(
            model_name='attemptthreshold',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_attempt_thresholds', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attemptthreshold',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_attempt_thresholds', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attemptsequential',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Attempt'),
        ),
        migrations.AddField(
            model_name='attemptsequential',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sequential_attempts', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attemptsequential',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_sequential_attempts', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_attempts', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Heat'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_attempts', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.PerformanceState'),
        ),
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_areas', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='area',
            name='field_of_play',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.FieldOfPlay'),
        ),
        migrations.AddField(
            model_name='area',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_areas', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationvote',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Annotation'),
        ),
        migrations.AddField(
            model_name='annotationvote',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_annotation_votes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationvote',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationvote',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_annotation_votes', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_annotation_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_annotation_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationsplit',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_annotation_splits', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationsplit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_annotation_splits', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationsplit',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Performance'),
        ),
        migrations.AddField(
            model_name='annotationattemptthreshold',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Attempt'),
        ),
        migrations.AddField(
            model_name='annotationattemptthreshold',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_threshold_attempt_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationattemptthreshold',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_threshold_attempt_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationattemptsequential',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.Attempt'),
        ),
        migrations.AddField(
            model_name='annotationattemptsequential',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sequential_attempt_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotationattemptsequential',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_sequential_attempt_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletics.AnnotationType'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_annotations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity'),
        ),
        migrations.AlterUniqueTogether(
            name='stagingrelaysplit',
            unique_together={('staging_performance', 'staging_identity')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingrelayperformanceparticipants',
            unique_together={('performance', 'relay', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingrelaymembers',
            unique_together={('staging_relay', 'staging_identity')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingperformance',
            unique_together={('staging_heat', 'staging_organization_id', 'staging_identity_id', 'squad', 'value', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingheat',
            unique_together={('staging_competition', 'staging_tier', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingattemptthreshold',
            unique_together={('attempt', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='stagingattemptsequential',
            unique_together={('attempt', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='socialclassalias',
            unique_together={('social_class', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesmeet',
            unique_together={('series', 'meet')},
        ),
        migrations.AlterUniqueTogether(
            name='serieshierarchy',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='seed',
            unique_together={('competition', 'identity', 'seed_method', 'seed_source_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewflag',
            unique_together={('user', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='relaysplit',
            unique_together={('performance', 'identity')},
        ),
        migrations.AlterUniqueTogether(
            name='relayperformanceparticipant',
            unique_together={('performance', 'relay', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='relaymember',
            unique_together={('relay', 'identity')},
        ),
        migrations.AlterUniqueTogether(
            name='performancesimilarity',
            unique_together={('performance', 'other')},
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('heat', 'organization', 'identity', 'squad', 'value', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='meetinstancereview',
            unique_together={('meet_instance', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='heatsimilarity',
            unique_together={('heat', 'other')},
        ),
        migrations.AlterUniqueTogether(
            name='heatclusteringassignments',
            unique_together={('clustering', 'performance', 'cluster')},
        ),
        migrations.AlterUniqueTogether(
            name='heatclustering',
            unique_together={('heat', 'id', 'min_eps', 'min_points', 'max_eps', 'max_points', 'fuzzy')},
        ),
        migrations.AlterUniqueTogether(
            name='heat',
            unique_together={('competition', 'tier', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='disqualification',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesurface',
            unique_together={('course', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesimilarity',
            unique_together={('course', 'other')},
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together={('course', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionsimilarity',
            unique_together={('competition', 'other')},
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('meet_instance', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='categorymeet',
            unique_together={('meet', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryhierarchy',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptthreshold',
            unique_together={('attempt', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptsequential',
            unique_together={('attempt', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='annotationvote',
            unique_together={('annotation', 'identity', 'up', 'down')},
        ),
    ]
