# Generated by Django 3.1.4 on 2021-01-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='weather_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weather_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weather_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.location'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.venue'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='venue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.venuetype'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.location'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.venue'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.amenity'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.address'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.location'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.locationtype'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='address_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.addresscomponent'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.location'),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.language'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.currency'),
        ),
        migrations.AddField(
            model_name='countrycodes',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.continent'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='amenity_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='amenity_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='amenity_last_modified', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='address_component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.addresscomponenttype'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_created_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='address',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_deleted_by', to='identity.identity'),
        ),
        migrations.AddField(
            model_name='address',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_last_modified', to='identity.identity'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('location', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='venuetypes',
            unique_together={('venue_type', 'venue')},
        ),
        migrations.AlterUniqueTogether(
            name='venuelocations',
            unique_together={('venue', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='venueamenities',
            unique_together={('venue', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='locationtypes',
            unique_together={('location_type', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='locationaddress',
            unique_together={('address_component', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='countrycurrency',
            unique_together={('country', 'currency')},
        ),
    ]
