# Generated by Django 2.2.11 on 2020-07-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='weather_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weather_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Location'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuetypes_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuetypes_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Venue'),
        ),
        migrations.AddField(
            model_name='venuetypes',
            name='venue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.VenueType'),
        ),
        migrations.AddField(
            model_name='venuetype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuetype_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuetype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuetype_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuelocations_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venuelocations_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Location'),
        ),
        migrations.AddField(
            model_name='venuelocations',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Venue'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Amenity'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venueamenities_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='last_modified_by',
            field=models.ForeignKey(db_column='last_modified_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venueamenities_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='venue',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='terrain_created_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terrain_last_modified_by', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_location_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_location_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Location'),
        ),
        migrations.AddField(
            model_name='locationtypes',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.LocationType'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_location_type', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_location_type', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='address_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.AddressComponent'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_location_addresses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_location_addresses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_locations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='location',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_locations', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_language_variants', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Language'),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_language_variants', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='language',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_languages', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='language',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_languages', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_currencies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='currency',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_currencies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Country'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_country_currencies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Currency'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_country_currencies', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='countrycodes',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Continent'),
        ),
        migrations.AddField(
            model_name='continent',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_continents', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='continent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_continents', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_amenities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_amenities', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='addresscomponenttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_address_component_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='addresscomponenttype',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_address_component_types', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='address_component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.AddressComponentType'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_address_components', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_address_components', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_addresses', to='identity.Identity'),
        ),
        migrations.AddField(
            model_name='address',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_addresses', to='identity.Identity'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('location', 'date', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='venuetypes',
            unique_together={('venue_type', 'venue')},
        ),
        migrations.AlterUniqueTogether(
            name='venuelocations',
            unique_together={('venue', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='venueamenities',
            unique_together={('venue', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='locationtypes',
            unique_together={('location_type', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='locationaddress',
            unique_together={('address_component', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='countrycurrency',
            unique_together={('country', 'currency')},
        ),
    ]
