# Generated by Django 2.2.11 on 2020-07-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('wikipedia_url', models.CharField(max_length=150)),
                ('symbol', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantity_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantity_last_modified_by', to='identity.Identity')),
            ],
            options={
                'db_table': 'quantity',
            },
        ),
        migrations.CreateModel(
            name='UnitSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('wikipedia_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='unitsystem_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unitsystem_last_modified_by', to='identity.Identity')),
            ],
            options={
                'db_table': 'unit_system',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('acronym', models.CharField(max_length=5)),
                ('abbreviation', models.CharField(max_length=10)),
                ('wikipedia_url', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_last_modified_by', to='identity.Identity')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.Quantity')),
                ('unit_system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.UnitSystem')),
            ],
            options={
                'db_table': 'unit',
                'unique_together': {('unit_system', 'quantity', 'name')},
            },
        ),
        migrations.AddField(
            model_name='quantity',
            name='si_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='si_quantity', to='utility.Unit', null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('image_content_url', models.CharField(blank=True, max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('article_body', models.CharField(max_length=2000)),
                ('wikipedia', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledgegraph_created_by', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledgegraph_last_modified_by', to='identity.Identity')),
            ],
            options={
                'db_table': 'knowledge_graph',
            },
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_feedback_types', to='identity.Identity')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_feedback_types', to='identity.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.FeedbackType')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='identity.Identity')),
            ],
        ),
    ]
